### ISSUE TITLE
The installer doesn't work on Windows Server

### ISSUE THREAD

**Issue by cakrit** [netdata/msi-installer#10]
We provisioned one (not sure version) that's accessible via RDP. The installer ran, I see NetdataWSL in the programs, but no wsl and no netdata running.

I will send you the rdp credentials @dfpr

**Comment by dfpr** [comment]
send them, I'll check what happened

**Comment by cakrit** [comment]
I think that the following may be the issue both for this and for #11 

> If WSL is not installed, the installer will add it and reboot the server. After restart, run the MSI again manually. 

The windows server didn't have WSL. The installer didn't reboot the server. Rerunning the same msi twice is a bit counterintuitive. Which which options the first time and which the second?

**Comment by cakrit** [comment]
Regardless of what the README says, we should make this process as self-evident as possible. rerunning the same thing is a bit confusing. Suggest options and let's see what we'll do.

**Comment by dfpr** [comment]
I'll test on a fresh server, it is possible the WSL Windows feature installation command for Client editions is different for Server Roles. For the re-run step I'll try putting the installer in the temp dir and set it to run with a RunOnce key in order to finish the installation.

**Comment by cakrit** [comment]
Sound great, thanks.

**Comment by dfpr** [comment]
Installer has been updated and does run on Windows Server now.

**Comment by cakrit** [comment]
I can't get it to work on the server I sent you the RDP info on:
- I first tried to uninstall the older installation, as the wsl distribution netdata existed. 
  - It didn't appear in the Add/remove programs. 
  - I removed a "WSL update" that did nothing. 
  - I found an article that said I could run `wsl --unregister <distribution>` and I did that, which did remove the distribution.
 - I ran the new installer and it seems to do its job, but it's as if the previous `--unregister` has affected things, because the distribution refuses to appear and run. NetdataWSL does now appear under add/remove programs and can be uninstalled. Restarts don't seem to do anything.

I suspect I screwed something up with the unregister command, but I have no idea how to recover. Can you log in and see if you can figure it out?

**Comment by dfpr** [comment]
I won't be able today but I think the june update makes the wsl command behavior inconsistent, I'll check with an updated system as soon as I can

**Comment by dfpr** [comment]
I have added steps in the installer to enable the Virtual Machine Platform feature and install the WSL2 kernel update requirements that were missing for setup on Windows Server.
For the machine that was available through RDP, since it is a VM that doesn't have virtualization support and the installer aims to use WSL2, most likely issues will continue in that scenario. Regular non-virtualized Windows Server machines should work.

**Comment by cakrit** [comment]
In https://github.com/netdata/msi-installer/issues/15 I clarified that supporting WSL1 is inevitable. So please add back the revert to WSL1 if WSL2 fails and retry on this VM. We're working on the netdata bug (not being able to kill netdata) as well.

**Comment by dfpr** [comment]
In order to fix this I will test in Windows server with the WSL2 update installed and when not and when virtualization is or isn't available so the best route is taken.

**Comment by cakrit** [comment]
Yes, sounds good. Need any help from me to do that?

**Comment by dfpr** [comment]
> Yes, sounds good. Need any help from me to do that?

I can handle it, thanks.

**Comment by dfpr** [comment]
This has been fixed.

**Comment by cakrit** [comment]
Indeed it worked. Attaching the log from our Windows Server which has some confusing errors in it, but is very otherwise very clear about what happened:

[netdata.log](https://github.com/netdata/msi-installer/files/9952729/netdata.log)

 I will reinstall once more with the claiming info and close this if everything is ok.

**Comment by cakrit** [comment]
It worked, the log issue is a different one. There's also a problem in that the installation is no longer unattended, which is going into a new issue I'm opening now.
