### ISSUE TITLE
Node is seen Unseen on Cloud and can't find logs to troubleshoot

### ISSUE THREAD

**Issue by hugovalente-pm** [netdata/msi-installer#11]
I see my node claimed but as Unseen some issue on the communication between Agent and Cloud, was trying to search for logs and can't find them

<image src="https://user-images.githubusercontent.com/82235632/198683816-0aa4cdfd-ac7c-49e6-a486-25d19de5e671.png" height="60%" width="60%"/>

**Comment by hugovalente-pm** [comment]
cc/ @cakrit

**Comment by cakrit** [comment]
Issue #9 is for the log files. 

Which windows version did you use?

Send me the command you used, we'll probably need to rerun adding `/L*V "C:\log\example.log"`, to see what the installer says.

**Comment by cakrit** [comment]
FYI for now @dfpr

**Comment by dfpr** [comment]
For this it seems the installation and claiming worked so MSI Windows Installer logs won't show the issue, better check netdata logs after https://github.com/netdata/msi-installer/issues/9 is resolved.

**Comment by hugovalente-pm** [comment]
ok, will still generate the log

my Windows version details
<image src="https://user-images.githubusercontent.com/82235632/198695983-c74ecc4e-47e6-4b3e-ac59-dbc26b6a30a2.png" height="60%" width="60%"/>

**Comment by dfpr** [comment]
> ok, will still generate the log
> 
> my Windows version details <img alt="" width="60%" height="60%" src="https://user-images.githubusercontent.com/82235632/198695983-c74ecc4e-47e6-4b3e-ac59-dbc26b6a30a2.png">

Try killing the agent and launching again with these to see if appears in cloud:
```
wsl -t netdata
wsl -d netdata netdata
```

**Comment by hugovalente-pm** [comment]
@dfpr I've run the two commands provided

<image src="https://user-images.githubusercontent.com/82235632/198731813-1fbd5314-c8bb-4721-aa49-0e1a61aec4eb.png" height="100%" width="100%"/>

**Comment by hugovalente-pm** [comment]
i think it is because I have another local instance running (Ubuntu) now that I see better the error, let me stop that one

**Comment by dfpr** [comment]
Logs at /var/log/netdata have been fixed.

**Comment by hugovalente-pm** [comment]
was able to get the Node live! I couldn't find the logs folder can you share where I should look for it @dfpr ?

now also trying to dig into a different problem because I only get a small subset of charts
![image](https://user-images.githubusercontent.com/82235632/199051443-932fe9c0-dcc5-4565-9318-8d9f8ff71eca.png)

**Comment by dfpr** [comment]
> was able to get the Node live! I couldn't find the logs folder can you share where I should look for it @dfpr ?

The agent logs located at /var/log/netdata inside the Netdata distro (and all the distro files) can be reached in addition from the terminal (```wsl -d netdata```) through the Netdata folder inside the Linux item located in the folder tree on the Windows File Explorer or going to the "\\wsl.localhost\netdata\var\log\netdata" Windows path.

> now also trying to dig into a different problem because I only get a small subset of charts !

For that issue please try to restart the computer after installation. Sometimes instead of a full restart stopping the agent (```wsl -d netdata netdatacli shutdown-agent```) and starting it again (```wsl -d netdata netdata```) and/or restarting the windows_exporter service by running (```Restart-Service windows_exporter```) in an elevated Powershell terminal can fix the WMI metrics not showing.

**Comment by hugovalente-pm** [comment]
> ...or going to the "\wsl.localhost\netdata\var\log\netdata" Windows path.

I actually got there from `\\wsl$\netdata\var\log\netdata` and I can see the logs so 👌 

> and/or restarting the windows_exporter service by running 

I think this maybe the issue, I tried to stop the agent but it isn't responding let me restart the laptop

**Comment by hugovalente-pm** [comment]
I did the laptop restart and couldn't see the other charts, I'm trying again to stop the agent (wsl -d netdata netdatacli shutdown-agent) to start it again but it seems to get _stuck_

![image](https://user-images.githubusercontent.com/82235632/199074061-6cb6bffd-6173-411d-b808-710007b5a2cc.png)

**Comment by cakrit** [comment]
don't use netdatacli, it's broken. Just do `wsl -d Netdata killall netdata` to stop Netdata. I updated the README.

**Comment by cakrit** [comment]
Closing this, we have #12

**Comment by dfpr** [comment]
@hugovalente-pm latest version saves installation log at c:\netdata.log.
