### ISSUE TITLE
Verify prerequisite?

### ISSUE THREAD

**Issue by cakrit** [netdata/msi-installer#13]
Is it possible to warn the user if the prerequisite of the wmi windows_exporter isn't satisfied?

https://learn.netdata.cloud/docs/agent/collectors/go.d.plugin/modules/wmi#requirements

What options do we have?

**Comment by dfpr** [comment]
I'm thinking of checking if http://localhost:9182/ works, if not installation would intentionally fail.
Additionally, setting up an installation log created at %userprofile%\appdata\local\temp (C:\Users\User\AppData\Local\Temp) for troubleshooting a failed installation.

**Comment by cakrit** [comment]
Do just that for this ticket. I'll add another one to optionally provide a WINDOWS_EXPORTER_URL parameter, as the exporter can optionally be installed on a different port.

**Comment by cakrit** [comment]
I won't do it now though, let's finish all the other things first.

**Comment by cakrit** [comment]
Before we do this, a question: I see that it's possible to have msi packages that also install msi packages. 
I'm not really keen on including whatever the latest windows_exporter msi is as the only way to install, because that would mean we'd have to support all the options they provide as well. So, a nightmare. 
But perhaps we could do the following?
- Have a default installation with no parameters allowed for the windows_exporter, where we do fetch and install their latest msi (or include it, not sure how it works). 
- If a user provides a WINDOWS_EXPORTER_URL=XYZ parameter, then we do not fetch and install the windows_exporter. instead, we verify that the URL works. 

We would then tell users that for a default windows_exporter installation they just use our msi, but if they want something more advanced, they'll need to install it themselves and give us the URL.

**Comment by dfpr** [comment]
During a MSI installation Windows Installer blocks concurrent installations so one MSI can't install other, what can be done is pack two or more into an EXE setup file that will install them sequentially, but that wouldn't work for domain policy deployments that can only use MSI.
________________________________

**Comment by cakrit** [comment]
I verified the installation of windows_exporter on Windows 11 and Windows Server
