### ISSUE TITLE
Fix /etc/netdata/go.d/wmi.conf

### ISSUE THREAD

**Issue by cakrit** [netdata/msi-installer#2]
It now says
```
jobs:
  - name: DESKTOP-C7OKV71
    url: http://127.0.0.1:9182/metrics
```

`name` should have the output of $(hostname)
`url` should have the output of $(hostname).local

The localhost IP doesn't work in my case, not sure if it works anywhere, as it references the linux instance. 

```
DESKTOP-C7OKV71:/usr/libexec/netdata/plugins.d# ./go.d.plugin -d -m wmi_exporter
...
[ ERROR ] wmi[DESKTOP-C7OKV71] wmi.go:91 Get "http://127.0.0.1:9182/metrics": dial tcp 127.0.0.1:9182: connect: connection refused
[ ERROR ] wmi[DESKTOP-C7OKV71] job.go:191 check failed
```

**Comment by cakrit** [comment]
The new nightly has the improvement from https://github.com/netdata/netdata/issues/13716, so from tomorrow we shouldn't need this config file at all. Please remove it @dfpr

**Comment by ilyam8** [comment]
Added in https://github.com/netdata/go.d.plugin/pull/941

```YAML
jobs:
  - name: wsl-local
    url: http://hostname.local:9182/metrics
```

"hostname" will be replaced with [hostname](https://man7.org/linux/man-pages/man1/hostname.1.html) result when reading the config.

**Comment by dfpr** [comment]
> The new nightly has the improvement from [netdata/netdata#13716](https://github.com/netdata/netdata/issues/13716), so from tomorrow we shouldn't need this config file at all. Please remove it @dfpr

I will remove tomorrow and test then.

**Comment by dfpr** [comment]
Removed the file and tested it is working.
