### ISSUE TITLE
Upgrades should auto-remove older versions

### ISSUE THREAD

**Issue by shyamvalsan** [netdata/msi-installer#20]
Currently when I try installing a newer version of netdata.msi it errors out saying netdata is Already installed.

This scenario should be handled by prompting the user if they want to remove existing Netdata versions and proceed with the installation.

**Comment by dfpr** [comment]
The MSI upgrade process will be fixed soon, meanwhile uninstalling before upgrading is the only possibility, thank you for your feedback.

**Comment by cakrit** [comment]
Closing in favor of #6
