### ISSUE TITLE
Reason for restarting?

### ISSUE THREAD

**Issue by cakrit** [netdata/msi-installer#21]
If WSL is already installed, do we really need to restart the server after uninstalling and reinstalling netdata? what's the purpose?

Will this go away with the proper handling of updates? i.e. people will just be running the new installer and no windows host restart necessary?

**Comment by dfpr** [comment]
That's correct, only fresh installations would need a restart, I'll finish the upgrade process today.

**Comment by cakrit** [comment]
Thanks
