### ISSUE TITLE
The installation is not unattended

### ISSUE THREAD

**Issue by cakrit** [netdata/msi-installer#22]
I installed on the Windows Server which we access via Remote Desktop. After the restart, the installation does not finish until I reconnect to the server via Remote Desktop. The installation should start and complete without anyone logging in.

**Comment by dfpr** [comment]
In order to fix this, since WSL distributions are registered per user and not globally (https://github.com/microsoft/WSL/issues/2979) WSL will need to work as a Windows Service first.

**Comment by cakrit** [comment]
Ugh, this is horrible. So there's no workaround for sysadmins who'd want to install this on hundreds of servers? e.g. Does any tooling they have allow them to emulate a login to allow such things to work?

**Comment by cakrit** [comment]
We can't do anything about this, we won't be recommending the installer for production use because of it and other issues with WSL
