### ISSUE TITLE
Add the other two parameters for claiming

### ISSUE THREAD

**Issue by cakrit** [netdata/msi-installer#4]
TOKEN is there, please add ROOMS and URL as well, as per https://github.com/netdata/msi-installer/issues/1#issue-1411973021

**Comment by Ferroin** [comment]
Note that the URL can (and probably should) default to `https://app.netdata.cloud` if not supplied (for consistency with our installers on Linux.

**Comment by dfpr** [comment]
Added the two parameters, rooms and URL in addition to a telemetry control, for claiming only token is mandatory and URL defaults to https://api.netdata.cloud

**Comment by cakrit** [comment]
Ran it, works fine

**Comment by cakrit** [comment]
One correction, FYI the default is app.netdata.cloud, not api.netdata.cloud. I added https://github.com/netdata/msi-installer/pull/8 and directly committed a correction to the readme. make sure you fetch before you commit new changes, to prevent conflicts.

Also, a question, how do the properties work regardless of their order? From https://github.com/netdata/msi-installer/blob/master/src/MSIhelper2.cmd#L7 it looks like they must be given in their exact order, i.e. we need all of them, or none of them. But there must be something  I missed makes passing just the telemetry parameter work, because I ran the msi just with telemetry=0 and it worked fine.

**Comment by dfpr** [comment]
> One correction, FYI the default is app.netdata.cloud, not api.netdata.cloud. I added #8 and directly committed a correction to the readme. make sure you fetch before you commit new changes, to prevent conflicts.
> 
> Also, a question, how do the properties work regardless of their order? From https://github.com/netdata/msi-installer/blob/master/src/MSIhelper2.cmd#L7 it looks like they must be given in their exact order, i.e. we need all of them, or none of them. But there must be something I missed makes passing just the telemetry parameter work, because I ran the msi just with telemetry=0 and it worked fine.

For the MSI the argument order is not important, Windows installer parses them and sets the properties either way, but the helper script uses a strict order set by Windows Installer (https://github.com/netdata/msi-installer/blob/master/src/NetdataWSL%20Windows%20Installer.wxs#L41), that shouldn't be an issue as the cmd is run internally and controlled by Windows Installer.
