### ISSUE TITLE
Sign the installer

### ISSUE THREAD

**Issue by cakrit** [netdata/msi-installer#7]
I'm purchasing a Windows Code Signing Certificate, so that we don't get warnings from the installer. 

I'll send its info privately so we can sign the msi, while we wait for the verification process.

**Comment by cakrit** [comment]
Actually, @dfpr it's been ages since I last signed an installer, so what will you need from me? The csr and the private key?

**Comment by dfpr** [comment]
> Actually, @dfpr it's been ages since I last signed an installer, so what will you need from me? The csr and the private key?

@cakrit yes, the public-private key pair should be enough to sign the MSI file.

**Comment by cakrit** [comment]
As we saw, it doesn't seem to work this way and we'll probably need to wait for the Certificate Authority to verify the company. This process is in progress.

**Comment by cakrit** [comment]
Done.
